# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central', models.CharField(max_length=200)),
                ('condominio', models.CharField(max_length=200)),
                ('apartamento', models.IntegerField()),
                ('descricao', models.TextField(max_length=300)),
                ('liberacao', models.CharField(max_length=200)),
                ('data', models.DateField()),
            ],
        ),
    ]
