# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0002_auto_20171018_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_descricao',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
    ]
