# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0003_auto_20171018_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_descricao',
            new_name='Post',
        ),
    ]
