# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0006_post_arquivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_arquivo',
            new_name='Arquivo',
        ),
    ]
