# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0007_auto_20171104_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arquivo',
            new_name='Delete',
        ),
    ]
