# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0008_auto_20171104_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delete',
            old_name='data_modificacao',
            new_name='data_exclusao',
        ),
    ]
