# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0010_auto_20171120_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='condominio',
            old_name='Observações',
            new_name='observacao',
        ),
        migrations.AlterField(
            model_name='central',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descricao.Usuario'),
        ),
    ]
