# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0011_auto_20171120_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='central',
            old_name='Central',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='central',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descricao.Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nome_operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descricao.Usuario'),
        ),
    ]
